export const categories = [
  "latest",
  "news",
  "sport",
  "tech",
  "world",
  "finance",
  "politics",
  "business",
  "economics",
  "entertainment",
  "beauty",
  "travel",
  "music",
  "food",
  "science",
  "gaming",
  "energy",
  "saved",
];

export const newsData = {
  status: "ok",
  total_hits: 10000,
  page: 1,
  total_pages: 200,
  page_size: 50,
  articles: [
    {
      title: "10 Things To Know About The Tesla Roadster",
      author: "James Bimson",
      published_date: "2023-07-02 12:30:15",
      published_date_precision: "full",
      link: "https://www.hotcars.com/things-to-know-tesla-roadster/",
      clean_url: "hotcars.com",
      excerpt:
        "We already know that the Tesla Roadster is six years late to the EV supercar party, but when it does arrive, it will come ready to take on the world.",
      summary:
        "Tesla launched the first-generation Roaster in 2008 as the company's flagship EV. It's fair to say the pioneering \nEV manufacturer has gone from strength to strength\n, since, even \nlaunching Musk's original car into space back in 2018\n! While Elon's Tesla has gone on to tease the Cybertruck and the Tesla Semi alongside their growing sedan and SUV range, there remains one nagging question \u2013 will there be a successor to the industry-changing roadster?\n \nBack in 2017, that question was answered when Musk announced the second-gen Tesla Roadster.",
      rights: "hotcars.com",
      rank: 17042,
      topic: "gaming",
      country: "US",
      language: "en",
      authors: "James Bimson",
      media:
        "https://static1.hotcarsimages.com/wordpress/wp-content/uploads/2023/06/tesla-roadster-1.jpg",
      is_opinion: false,
      twitter_account: "@HotcarsOfficial",
      _score: 13.218174,
      _id: "75e8d05beeca654d1873348ac27b77b3",
    },
    {
      title:
        "Tesla Nearing Third Party App Support: Could A Tesla App Store Be Next?",
      author: "Chris Katje",
      published_date: "2023-06-29 22:06:50",
      published_date_precision: "full",
      link: "https://www.benzinga.com/news/23/06/33068651/tesla-nearing-third-party-app-support-could-a-tesla-app-store-be-next",
      clean_url: "benzinga.com",
      excerpt:
        "Leading electric vehicle company Tesla Inc (NASDAQ: TSLA) announced several partnerships with leading automakers for sharing\u00a0its Supercharger network. This support might lead to third-party app support and an\u00a0app store coming.",
      summary:
        "Leading electric vehicle company Tesla Inc TSLA announced several partnerships with leading automakers for sharing its Supercharger network. This support might lead to third-party app support and an app store coming.\n\nWhat Happened: The center touchscreen inside Tesla vehicles supports video games and Zoom meetings. Tesla Arcade offers video games, but they come from direct partnerships and not as third-party apps.\n\nReports have pointed to Tesla starting to support third-party apps as the company looks to offer features for its vehicle owners.",
      rights: "benzinga.com",
      rank: 1933,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Chris Katje",
      media:
        "https://cdn.benzinga.com/files/images/story/2023/06/29/tesla.alexander-shatov-gv6b0bphag0-unsplash.jpg?width=1200&height=800&fit=crop",
      is_opinion: false,
      twitter_account: "@benzinga",
      _score: 13.20905,
      _id: "7f7009df5ac20d00ffbd281fc52b0184",
    },
    {
      title:
        "Tesla Second Quarter Deliveries Up 83% \u2014 8% Ahead Of Estimates",
      author: "Peter Cohan",
      published_date: "2023-07-02 19:00:02",
      published_date_precision: "full",
      link: "https://www.forbes.com/sites/petercohan/2023/07/02/tesla-second-quarter-deliveries-up-83---8-ahead-of-estimates/",
      clean_url: "forbes.com",
      excerpt:
        "If Tesla accomplished the result by cutting prices, revenues and profit margins could fall short of investors expectations.",
      summary:
        "Tesla reported expectations-beating deliveries in its second quarter. The implications of this result for investors depends on how Tesla achieved those deliveries.\n\nIf Tesla accomplished the result by cutting prices, revenues and profit margins could fall short of investors expectations. If that happens, Tesla's stock price could fall \u2014 unless it raises its guidance for the third quarter.\n\nOn July 19, Tesla \u2014 3.5% of its shares are sold short, according to the Wall Street Journal \u2014 will issue its second quarter earnings report and settle the question.",
      rights: "Copyright 2023 Forbes Media LLC",
      rank: 49,
      topic: "business",
      country: "US",
      language: "en",
      authors: "Peter Cohan",
      media:
        "https://imageio.forbes.com/specials-images/imageserve/64a1b625a7dc766441b4ddd4/0x0.jpg?format=jpg&width=1200",
      is_opinion: false,
      twitter_account: "@forbes",
      _score: 13.135572,
      _id: "06f67d8dd61507ff1a2dd085f9e3c787",
    },
    {
      title: "Tesla Deliveries Hit Record 466,140, Crushing Q2 Views",
      author: "KIT NORTON",
      published_date: "2023-07-02 16:24:15",
      published_date_precision: "full",
      link: "https://www.investors.com/news/tesla-deliveries-q2-record-tesla-stock/",
      clean_url: "investors.com",
      excerpt: "Tesla stock has more than doubled in 2023.",
      summary:
        "Tesla (TSLA) reported record global deliveries on Sunday, as price cuts and discounts propelled demand well above Wall Street forecasts.\n\nTesla Deliveries\n\nTesla deliveries ran to 466,140 in the second quarter, sprinting past Q1's record 422,875 and Q4's 405,278. That easily beat Q2 estimates of around 445,000, according to FactSet.\n\nModel 3 and Y deliveries hit 446,915 in Q2. Model S and X deliveries picked up to 19,225.\n\nProduction hit 479,700, exceeding deliveries once again, even with Tesla curbing output below capacity.",
      rights: "investors.com",
      rank: 2523,
      topic: "news",
      country: "US",
      language: "en",
      authors: "KIT NORTON",
      media:
        "https://www.investors.com/wp-content/uploads/2018/06/stock-tesla-model3-04-company.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: 13.124975,
      _id: "5de28e520efddafd0497ebd77ca24a1b",
    },
    {
      title:
        "\u0391\u03c5\u03c4\u03ac \u03b5\u03af\u03bd\u03b1\u03b9 \u03c4\u03b1 \u03b7\u03bb\u03b5\u03ba\u03c4\u03c1\u03b9\u03ba\u03ac \u03b1\u03c5\u03c4\u03bf\u03ba\u03af\u03bd\u03b7\u03c4\u03b1 \u03c0\u03bf\u03c5 \u03b8\u03b1 \u03bc\u03c0\u03bf\u03c1\u03bf\u03cd\u03bd \u03bd\u03b1 \u03c6\u03bf\u03c1\u03c4\u03af\u03b6\u03bf\u03c5\u03bd \u03c3\u03c4\u03bf\u03c5\u03c2 \u03c6\u03bf\u03c1\u03c4\u03b9\u03c3\u03c4\u03ad\u03c2 Tesla Superchargers \u03b1\u03c0\u03cc \u03c4\u03bf 2024",
      author:
        "\u0393\u03b9\u03ce\u03c1\u03b3\u03bf\u03c2 \u039a\u03b1\u03ba\u03b1\u03ba\u03b9\u03cc\u03c2",
      published_date: "2023-06-28 10:23:46",
      published_date_precision: "full",
      link: "https://gr.pcmag.com/cars-auto/44129/auta-einai-ta-elektrika-autokineta-pou-tha-mporoun-na-phortizoun-stous-phortistes-tesla-supercharger",
      clean_url: "pcmag.com",
      excerpt:
        "\u0395\u03ac\u03bd \u03ad\u03c7\u03b5\u03c4\u03b5 \u03ad\u03bd\u03b1 \u03b7\u03bb\u03b5\u03ba\u03c4\u03c1\u03b9\u03ba\u03cc \u03cc\u03c7\u03b7\u03bc\u03b1 \u03c4\u03b7\u03c2 Ford, \u03c4\u03b7\u03c2 General Motors, \u03c4\u03b7\u03c2 Rivian \u03ae \u03c4\u03b7\u03c2 Volvo, \u03b7 \u03c6\u03cc\u03c1\u03c4\u03b9\u03c3\u03ae \u03c4\u03bf\u03c5 \u03b8\u03b1 \u03b5\u03af\u03bd\u03b1\u03b9 \u03c3\u03cd\u03bd\u03c4\u03bf\u03bc\u03b1 \u03c0\u03b9\u03bf \u03b5\u03cd\u03ba\u03bf\u03bb\u03b7.",
      summary:
        "\u039f \u03c6\u03bf\u03c1\u03c4\u03b9\u03c3\u03c4\u03ae\u03c2 Tesla Supercharger (Credit: Tesla)\n\n\u039c\u03b9\u03b1 \u03c3\u03b7\u03bc\u03b1\u03bd\u03c4\u03b9\u03ba\u03ae \u03b1\u03bb\u03bb\u03b1\u03b3\u03ae \u03c3\u03c4\u03b7 \u03b2\u03b9\u03bf\u03bc\u03b7\u03c7\u03b1\u03bd\u03af\u03b1 \u03b7\u03bb\u03b5\u03ba\u03c4\u03c1\u03b9\u03ba\u03ce\u03bd \u03b1\u03c5\u03c4\u03bf\u03ba\u03b9\u03bd\u03ae\u03c4\u03c9\u03bd \u03ba\u03b1\u03b8\u03b9\u03c3\u03c4\u03ac \u03c4\u03b9\u03c2 \u03b8\u03cd\u03c1\u03b5\u03c2 \u03c6\u03cc\u03c1\u03c4\u03b9\u03c3\u03b7\u03c2 \u03b2\u03b1\u03c3\u03b9\u03ba\u03cc \u03c0\u03b1\u03c1\u03ac\u03b3\u03bf\u03bd\u03c4\u03b1 \u03ba\u03b1\u03c4\u03ac \u03c4\u03b7\u03bd \u03b5\u03c0\u03b9\u03bb\u03bf\u03b3\u03ae \u03c4\u03bf\u03c5 \u03b7\u03bb\u03b5\u03ba\u03c4\u03c1\u03b9\u03ba\u03bf\u03cd \u03bf\u03c7\u03ae\u03bc\u03b1\u03c4\u03bf\u03c2 \u03c0\u03bf\u03c5 \u03b8\u03b1 \u03b1\u03b3\u03bf\u03c1\u03ac\u03c3\u03b5\u03c4\u03b5 \u03ae \u03b3\u03b9\u03b1 \u03bd\u03b1 \u03b1\u03be\u03b9\u03bf\u03c0\u03bf\u03b9\u03ae\u03c3\u03b5\u03c4\u03b5 \u03c3\u03c4\u03bf \u03ad\u03c0\u03b1\u03ba\u03c1\u03bf \u03b1\u03c5\u03c4\u03cc \u03c0\u03bf\u03c5 \u03ad\u03c7\u03b5\u03c4\u03b5 \u03ae\u03b4\u03b7 \u03c3\u03c4\u03b7\u03bd \u03ba\u03b1\u03c4\u03bf\u03c7\u03ae \u03c3\u03b1\u03c2.\n\n\u03a4\u03bf\u03bd \u03c4\u03b5\u03bb\u03b5\u03c5\u03c4\u03b1\u03af\u03bf \u03bc\u03ae\u03bd\u03b1, \u03c4\u03ad\u03c3\u03c3\u03b5\u03c1\u03b9\u03c2 \u03bc\u03b5\u03b3\u03ac\u03bb\u03b5\u03c2 \u03b1\u03c5\u03c4\u03bf\u03ba\u03b9\u03bd\u03b7\u03c4\u03bf\u03b2\u03b9\u03bf\u03bc\u03b7\u03c7\u03b1\u03bd\u03af\u03b5\u03c2 \u03b4\u03ae\u03bb\u03c9\u03c3\u03b1\u03bd \u03cc\u03c4\u03b9 \u03b8\u03b1 \u03c3\u03c4\u03c1\u03b1\u03c6\u03bf\u03cd\u03bd \u03c3\u03c4\u03b7 \u03b8\u03cd\u03c1\u03b1 \u03c6\u03cc\u03c1\u03c4\u03b9\u03c3\u03b7\u03c2 \u03c4\u03b7\u03c2 Tesla. \u03a0\u03c1\u03cc\u03ba\u03b5\u03b9\u03c4\u03b1\u03b9 \u03b3\u03b9\u03b1 \u03c4\u03b9\u03c2 Ford, General Motors, \u03ba\u03b1\u03b9 . \u0391\u03c0\u03cc \u03c4\u03bf 2024, \u03bf\u03b9 \u03bf\u03b4\u03b7\u03b3\u03bf\u03af \u03b8\u03b1 \u03ad\u03c7\u03bf\u03c5\u03bd \u03c0\u03c1\u03cc\u03c3\u03b2\u03b1\u03c3\u03b7 \u03c3\u03b5 12.000 \u03c6\u03bf\u03c1\u03c4\u03b9\u03c3\u03c4\u03ad\u03c2 Tesla Superchargers \u03bc\u03ad\u03c3\u03c9 \u03b5\u03bd\u03cc\u03c2 \u03c0\u03c1\u03bf\u03c3\u03b1\u03c1\u03bc\u03bf\u03b3\u03ad\u03b1.",
      rights: "pcmag.com",
      rank: 492,
      topic: "news",
      country: "US",
      language: "el",
      authors:
        "\u0393\u03b9\u03ce\u03c1\u03b3\u03bf\u03c2 \u039a\u03b1\u03ba\u03b1\u03ba\u03b9\u03cc\u03c2,\u03a6\u03bf\u03b9\u03c4\u03b7\u03c4\u03ae\u03c2 \u03a0\u03b1\u03c1\u03b1\u03c3\u03c4\u03b1\u03c4\u03b9\u03ba\u03ce\u03bd \u03a4\u03b5\u03c7\u03bd\u03ce\u03bd",
      media:
        "https://sm.pcmag.com/t/pcmag_gr/news/h/here-are-t/here-are-the-evs-that-can-charge-at-tesla-superchargers-star_evnh.1200.jpg",
      is_opinion: false,
      twitter_account: "@PCMagGR",
      _score: 13.072916,
      _id: "2eb0541f093726647f45ca4c34b4e4f4",
    },
    {
      title: "Telsa dips toes into online advertisements",
      author: "Maria Merano",
      published_date: "2023-06-28 07:45:48",
      published_date_precision: "full",
      link: "https://www.teslarati.com/tesla-advertisements-online/",
      clean_url: "teslarati.com",
      excerpt:
        "Tesla recently dipped its toes into online advertisements, launching at least 18 ads on Google.",
      summary:
        "Tesla recently dipped its toes into online advertisements, launching at least 18 ads on Google. Elon Musk has long resisted the idea of Tesla using advertisements to promote its products. However, many TSLA shareholders and supporters believe ads might help dispel some of the false reports about Tesla and its products.\u00a0\n \nA quick search through Google reveals that Tesla didn't just launch advertisements for the company's all-electric vehicles but also for Tesla Energy products. The\u00a0\nTesla Google ads\n\u00a0appear straightforward, avoiding language that might confuse people.",
      rights: "teslarati.com",
      rank: 10191,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Maria Merano",
      media:
        "https://www.teslarati.com/wp-content/uploads/2023/06/tesla-model-y-rear-scaled.jpg",
      is_opinion: false,
      twitter_account: "@teslarati",
      _score: 13.068548,
      _id: "f718c1e396f9b92aab43c2e9f0c3e5aa",
    },
    {
      title: "Tesla Stock: No AI Hype Here",
      author: "Victor Dergunov",
      published_date: "2023-06-27 14:29:20",
      published_date_precision: "full",
      link: "https://seekingalpha.com/article/4613870-tesla-stock-no-ai-hype-here-buy-the-dip",
      clean_url: "seekingalpha.com",
      excerpt:
        "Tesla's recent run-up back toward a trillion dollar valuation has many analysts scratching their heads. Read why I am bullish on TSLA stock.",
      summary:
        "jetcityimage\n \nTesla, Inc.\n (\nNASDAQ:\nTSLA\n) stock has had quite a run-up since I discussed the bottom in the EV giant's share price in \nthe $100-120 range\n. We've seen Tesla's share price nearly triple, appreciating by approximately 180% since the\n stock price crashed to a bottom early this year. We've recently seen a 15% correction in Tesla's share price as Goldman Sachs (\nGS\n) and other investment houses came out with \"\ndowngrades\n\" after the six-month run-up in Tesla's stock.\n \nDespite being overbought in the near term, Tesla's stock offers significant intermediate and long-term potential.",
      rights: "seekingalpha.com",
      rank: 892,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Victor Dergunov",
      media:
        "https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1140204814/image_1140204814.jpg?io=getty-c-w1536",
      is_opinion: false,
      twitter_account: "@SeekingAlpha",
      _score: 13.033444,
      _id: "e22064fc74587ed867b46e2eea271fd1",
    },
    {
      title:
        "Sok-sokan Nyetir Mobil Tesla Pakai Autopilot, Pria Ini Malah Nabrak Truk Parkir",
      author: "Hendri Gusmulyadi",
      published_date: "2023-06-28 04:46:35",
      published_date_precision: "full",
      link: "https://pekanbaru.tribunnews.com/2023/06/28/sok-sokan-nyetir-mobil-tesla-pakai-autopilot-pria-ini-malah-nabrak-truk-parkir",
      clean_url: "tribunnews.com",
      excerpt:
        "Viral kasus kecelakaan yang melibatkan mobil Tesla yang terkenal akan kecanggihannya. Kejadian tabrak truk parkir saat pengemudi pakai autopilot",
      summary:
        "lihat foto\n \ntwitter.com/@metrofirepio\nTesla Model S terbakar di Jalan Tol California, Amerika Serikat. Ilustrasi .\u00a0\n \n \n \n \nTRIBUNPEKANBARU.COM - Tidak ada teknologi itu yang sempurna.\n \nPasti setiap produk teknologi yang diedarkan di pasaran punya kekurangan.\n \nHal itu yang dirasakan oleh pria pengemudi \nmobil\u00a0Tesla\n ini.\n \nViral kasus kecelakaan yang melibatkan \nmobil\u00a0Tesla\n yang\u00a0terkenal akan kecanggihannya.\n \nSaat melaju dalam mode otopilot, mobil ini malah\u00a0menabrak truk yang berhenti di pinggir jalan.",
      rights: "tribunnews.com",
      rank: 5860,
      topic: "news",
      country: "ID",
      language: "id",
      authors: "Hendri Gusmulyadi",
      media:
        "https://asset-2.tstatic.net/pekanbaru/foto/bank/images/Sok-sokan-Nyetir-Mobil-Tesla-Pakai-Autopilot-Pria-Ini-Malah-Nabrak-Truk-Parkir.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: 13.030367,
      _id: "6e8d79236945cb8c6f5f29be66e71c04",
    },
    {
      title: "How much does a Tesla cost? Prices of Model Y, X, S, and 3",
      author: "Graham Rier",
      published_date: "2023-06-28 19:20:00",
      published_date_precision: "full",
      link: "https://www.businessinsider.com/tesla-price-range-cost",
      clean_url: "businessinsider.com",
      excerpt:
        "Discover the Tesla price range and explore the true cost of owning an electric vehicle, including battery and charging considerations.",
      summary:
        "Tesla CEO Elon Musk has dropped the \nprices of Tesla models\n six times since the start of the year, kicking off \nTesla price wars\n with mainstream car brands like Ford and GM.\u00a0\nHere's a look at where the pricing stands for each of the models.\u00a0\nWhat is the cheapest Tesla model?\nThe \nTesla Model 3\n is the cheapest model. The starting price for the Tesla Model 3 is around $40,240 for the Real Wheel Drive, $47,240 for the Long Range variant, and $53,240 for the Performance variant.\nThe next cheapest model is the \nTesla Model Y\n.",
      rights: "Insider Inc. 2023",
      rank: 106,
      topic: "business",
      country: "US",
      language: "en",
      authors: "Business Insider,Graham Rapier",
      media:
        "https://i.insider.com/646b8cd42e229f001826815d?width=1200&format=jpeg",
      is_opinion: false,
      twitter_account: "@CarsInsider",
      _score: 13.023387,
      _id: "3ba93389e50a96ac760720ab05678254",
    },
    {
      title:
        "I own a \u00a344k Tesla Model S but here's ten reasons why you DON'T want it",
      author: "Jorge Hinojosa Mena",
      published_date: "2023-06-27 15:32:27",
      published_date_precision: "full",
      link: "https://www.thesun.co.uk/motors/22829440/own-tesla-reasons-why-you-dont-want-it/",
      clean_url: "thesun.co.uk",
      excerpt:
        "A TESLA owner has slammed the electric car after buying the Model S for a whopping \u00a344k \u2013 listing ten huge problems he's encountered. Myong Hong claims he's been inundated with is\u2026",
      summary:
        "A TESLA owner has slammed the electric car after buying the Model S for a whopping \u00a344k - listing ten huge problems he's encountered.\n\n\nMyong Hong claims he's been inundated with \nissues \nsince buying the car and even urged others not to buy the vehicle that has taken the world by storm.\u00a0\n\n\nA man who owns a \u00a344,000 Tesla Model S has revealed the ten key problems he has found in his electric cars\nCredit: YouTube @CameraToFreedom \n\n\nHe said that the price of charging your car varies depending on the time of the day, you can only repair your \nTesla \nat official repair centres, and they haven't included a spare tyre to make their car lighter.",
      rights: "thesun.co.uk",
      rank: 442,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "Jorge Hinojosa Mena",
      media:
        "https://www.thesun.co.uk/wp-content/uploads/2023/06/newspress-collage-22829440-1687872403929.jpg?1687876028&strip=all&quality=100&w=1920&h=1080&crop=1",
      is_opinion: false,
      twitter_account: "@thesun",
      _score: 13.022766,
      _id: "8f14303faccf111267366393c3d9ff36",
    },
    {
      title:
        "Solar D \u0e08\u0e31\u0e1a\u0e21\u0e37\u0e2d Tesla Energy \u0e08\u0e31\u0e14\u0e07\u0e32\u0e19 Tesla Energy Tech Talk",
      author: "\u0e02\u0e48\u0e32\u0e27\u0e2a\u0e14",
      published_date: "2023-06-28 07:54:00",
      published_date_precision: "full",
      link: "https://www.khaosod.co.th/pr-news/news_7737902",
      clean_url: "khaosod.co.th",
      excerpt:
        "Solar D \u0e08\u0e31\u0e1a\u0e21\u0e37\u0e2d Tesla Energy \u0e08\u0e31\u0e14\u0e07\u0e32\u0e19 Tesla Energy Tech Ta...",
      summary:
        "Solar D \u0e08\u0e31\u0e1a\u0e21\u0e37\u0e2d Tesla Energy \u0e08\u0e31\u0e14\u0e07\u0e32\u0e19 Tesla Energy Tech Talk \u0e40\u0e15\u0e34\u0e21\u0e40\u0e15\u0e47\u0e21\u0e01\u0e32\u0e23\u0e43\u0e0a\u0e49\u0e0a\u0e35\u0e27\u0e34\u0e15\u0e43\u0e2b\u0e49\u0e40\u0e2b\u0e19\u0e37\u0e2d\u0e23\u0e30\u0e14\u0e31\u0e1a \u0e1e\u0e23\u0e49\u0e2d\u0e21\u0e40\u0e23\u0e35\u0e22\u0e19\u0e23\u0e39\u0e49\u0e01\u0e32\u0e23\u0e40\u0e1b\u0e25\u0e35\u0e48\u0e22\u0e19\u0e1a\u0e49\u0e32\u0e19\u0e2a\u0e39\u0e48\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e17\u0e35\u0e48\u0e22\u0e31\u0e48\u0e07\u0e22\u0e37\u0e19\n\n21 \u0e21\u0e34\u0e16\u0e38\u0e19\u0e32\u0e22\u0e19 2566, \u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e\u0e2f \u2013 \u0e42\u0e0b\u0e25\u0e32\u0e23\u0e4c \u0e14\u0e35 \u0e04\u0e2d\u0e23\u0e4c\u0e1b\u0e2d\u0e23\u0e4c\u0e40\u0e23\u0e0a\u0e31\u0e19 (Solar D) \u0e1c\u0e39\u0e49\u0e19\u0e33\u0e14\u0e49\u0e32\u0e19\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e41\u0e2a\u0e07\u0e2d\u0e32\u0e17\u0e34\u0e15\u0e22\u0e4c \u0e19\u0e27\u0e31\u0e15\u0e01\u0e23\u0e23\u0e21\u0e23\u0e30\u0e1a\u0e1a\u0e08\u0e31\u0e14\u0e40\u0e01\u0e47\u0e1a\u0e41\u0e25\u0e30\u0e08\u0e31\u0e14\u0e01\u0e32\u0e23\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e44\u0e1f\u0e1f\u0e49\u0e32\u0e2a\u0e38\u0e14\u0e25\u0e49\u0e33\u0e2b\u0e19\u0e36\u0e48\u0e07\u0e40\u0e14\u0e35\u0e22\u0e27\u0e43\u0e19\u0e44\u0e17\u0e22 \u0e23\u0e48\u0e27\u0e21\u0e01\u0e31\u0e1a Tesla Energy \u0e08\u0e31\u0e14\u0e07\u0e32\u0e19 Tesla Energy Tech Talk \u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e19\u0e33\u0e40\u0e2a\u0e19\u0e2d\u0e42\u0e0b\u0e25\u0e39\u0e0a\u0e31\u0e19\u0e14\u0e49\u0e32\u0e19\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e41\u0e1a\u0e1a\u0e04\u0e23\u0e1a\u0e27\u0e07\u0e08\u0e23\u0e43\u0e2b\u0e49\u0e01\u0e31\u0e1a\u0e25\u0e39\u0e01\u0e04\u0e49\u0e32\u0e17\u0e38\u0e01\u0e23\u0e30\u0e14\u0e31\u0e1a \u0e1e\u0e23\u0e49\u0e2d\u0e21\u0e40\u0e1b\u0e34\u0e14\u0e42\u0e2d\u0e01\u0e32\u0e2a\u0e41\u0e25\u0e30\u0e40\u0e0a\u0e34\u0e0d\u0e0a\u0e27\u0e19\u0e43\u0e2b\u0e49\u0e1c\u0e39\u0e49\u0e17\u0e35\u0e48\u0e2a\u0e19\u0e43\u0e08\u0e43\u0e19\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e02\u0e2d\u0e07\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e42\u0e0b\u0e25\u0e32\u0e23\u0e4c\u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e1a\u0e49\u0e32\u0e19 Tesla Powerwall \u0e41\u0e25\u0e30\u0e23\u0e16\u0e22\u0e19\u0e15\u0e4c\u0e44\u0e1f\u0e1f\u0e49\u0e32 \u0e44\u0e14\u0e49\u0e40\u0e02\u0e49\u0e32\u0e21\u0e32\u0e40\u0e23\u0e35\u0e22\u0e19\u0e23\u0e39\u0e49\u0e41\u0e25\u0e30\u0e2a\u0e31\u0e21\u0e1c\u0e31\u0e2a\u0e1b\u0e23\u0e30\u0e2a\u0e1a\u0e01\u0e32\u0e23\u0e13\u0e4c\u0e27\u0e34\u0e18\u0e35\u0e01\u0e32\u0e23\u0e40\u0e1b\u0e25\u0e35\u0e48\u0e22\u0e19\u0e1a\u0e49\u0e32\u0e19\u0e02\u0e2d\u0e07\u0e17\u0e38\u0e01\u0e04\u0e19\u0e44\u0e1b\u0e2a\u0e39\u0e48\u0e1e\u0e25\u0e31\u0e07\u0e07\u0e32\u0e19\u0e2a\u0e30\u0e2d\u0e32\u0e14\u0e44\u0e14\u0e49\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e22\u0e31\u0e48\u0e07\u0e22\u0e37\u0e19 \u0e42\u0e14\u0e22\u0e44\u0e14\u0e49\u0e23\u0e31\u0e1a\u0e40\u0e01\u0e35\u0e22\u0e23\u0e15\u0e34\u0e08\u0e32\u0e01 \u0e19\u0e32\u0e22\u0e2a\u0e31\u0e21\u0e24\u0e17\u0e18\u0e34\u0e4c \u0e2a\u0e34\u0e17\u0e18\u0e34\u0e27\u0e23\u0e32\u0e19\u0e38\u0e27\u0e07\u0e28\u0e4c \u0e01\u0e23\u0e23\u0e21\u0e01\u0e32\u0e23\u0e1c\u0e39\u0e49\u0e08\u0e31\u0e14\u0e01\u0e32\u0e23 \u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e42\u0e0b\u0e25\u0e32\u0e23\u0e4c \u0e14\u0e35 \u0e04\u0e2d\u0e1b\u0e2d\u0e40\u0e23\u0e0a\u0e31\u0e19 \u0e08\u0e33\u0e01\u0e31\u0e14, \u0e19\u0e32\u0e22\u0e2a\u0e31\u0e19\u0e15\u0e34 \u0e28\u0e23\u0e35\u0e0a\u0e27\u0e32\u0e25\u0e32 \u0e01\u0e23\u0e23\u0e21\u0e01\u0e32\u0e23\u0e1c\u0e39\u0e49\u0e08\u0e31\u0e14\u0e01\u0e32\u0e23\u0e41\u0e25\u0e30\u0e1e\u0e31\u0e12\u0e19\u0e32\u0e18\u0e38\u0e23\u0e01\u0e34\u0e08 \u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e42\u0e0b\u0e25\u0e32\u0e23\u0e4c \u0e14\u0e35 \u0e04\u0e2d\u0e23\u0e4c\u0e1b\u0e2d\u0e40\u0e23\u0e0a\u0e31\u0e19, Mr.",
      rights: "khaosod.co.th",
      rank: 61783,
      topic: "news",
      country: "TH",
      language: "th",
      authors: "\u0e02\u0e48\u0e32\u0e27\u0e2a\u0e14",
      media: "https://www.khaosod.co.th/wpapp/uploads/2023/06/image1-491.jpg",
      is_opinion: false,
      twitter_account: "@KhaosodOnline",
      _score: 13.015899,
      _id: "465c9b7c617a152a497584f8d73018d6",
    },
    {
      title: "Tesla Stock Jumps. No Downgrade and Volvo Help.",
      author: "Al Root",
      published_date: "2023-06-27 14:05:00",
      published_date_precision: "full",
      link: "https://www.marketwatch.com/articles/tesla-stock-price-news-4f754b20?mod=mw_more_headlines",
      clean_url: "marketwatch.com",
      excerpt:
        "For the electric-vehicle maker, no news is good news after analysts bumped down its stock four times in four days.",
      summary:
        "To call recent trading in Tesla stock wild is to forget trading in Tesla stock is always wild.\n\nShares are up again. This time, a reason for what's propelling shares higher is what didn't happen.\n\nTesla shares (ticker: TSLA) were up 3.7% in late Tuesday trading, while the S&P 500 and Nasdaq Composite were up about 1.2% and 1.7%, respectively.\n\nThe big news is no news; the stock didn't get downgraded. Coming into Tuesday's trading, Tesla stock had been downgraded four times in four days, by Barclays, Morgan Stanley, DZ Bank, and Goldman Sachs.",
      rights: "marketwatch.com",
      rank: 274,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Al Root",
      media: "https://images.barrons.com/im-807609/social",
      is_opinion: false,
      twitter_account: "@marketwatch",
      _score: 12.999757,
      _id: "001f12b09fcc4ba381d238eac996b609",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://fox8.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "fox8.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "fox8.com",
      rank: 4925,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://fox8.com/wp-content/uploads/sites/12/2023/07/64a2c828ba1055.44769689.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.993004,
      _id: "9e8cadeeb7813706c2f522b2ea0935c3",
    },
    {
      title:
        "EV maker Polestar partners with Tesla to adopt its charging connector",
      author: "Matt Bernardini",
      published_date: "2023-06-29 23:57:59",
      published_date_precision: "full",
      link: "https://www.upi.com/Top_News/US/2023/06/29/Polestar-Tesla-charging-Ford-GM/1761688079060/",
      clean_url: "upi.com",
      excerpt:
        "Electric car maker Polestar said Thursday that it would partner with Tesla and adopt its technology for the charging of electric vehicles.",
      summary:
        "June 29 (UPI) --\n Electric car maker Polestar said Thursday that it would partner with Tesla and adopt its technology for the charging of electric vehicles.\n\n\nStarting in 2025, all new Polestar vehicles that are sold in North America will adopt Tesla's connector, known as the North American Charging Standard, over the current Combines Charging System standard, the company \nsaid\n.\n\n\n\n\"We salute the pioneering work Tesla has done to speed up the adoption and increase the popularity of electric vehicles, and it's great to see the Supercharger network being made available in this way,\" CEO Thomas Ingenlath said in a statement.",
      rights:
        "Copyright (c) 2023 United Press International, Inc. All Rights Reserved.",
      rank: 1104,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Matt Bernardini",
      media:
        "https://cdnph.upi.com/sv/ph/og/i/1761688079060/2023/1/16880796062241/v1.5/EV-maker-Polestar-partners-with-Tesla-to-adopt-its-charging-connector.jpg",
      is_opinion: false,
      twitter_account: "@UPI",
      _score: 12.992662,
      _id: "c9eca711fc3c3e815d1abebe005a1e8c",
    },
    {
      title:
        "Tesla beats second-quarter estimates with deliveries of 466,000 vehicles",
      author: "Clive McKeef",
      published_date: "2023-07-02 17:08:00",
      published_date_precision: "full",
      link: "https://www.marketwatch.com/story/tesla-beats-2nd-quarter-estimates-with-deliveries-of-466-000-vehicles-24efc14f",
      clean_url: "marketwatch.com",
      excerpt:
        "Tesla Inc. delivered a record number of vehicles in the second quarter, beating market estimates after the electric carmaker increased discounts and...",
      summary:
        "Tesla Inc. delivered a record number of vehicles in the second quarter, beating market estimates after the electric-car maker increased discounts and incentives, the company reported Sunday.\n \nThe Elon Musk-led electric vehicle manufacturer\n delivered 466,140 vehicles in the\n \nthree months ended June 30\n and produced 479,700 vehicles. The second quarter of 2023 marked the fifth period in a row when Tesla reported a higher level of vehicles produced compared to deliveries.\n \n \nAnalysts on average had expected Tesla to deliver 445,000 cars, according to analysts polled by Refinitiv.",
      rights: "marketwatch.com",
      rank: 274,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Clive McKeef",
      media: "https://images.mktw.net/im-805740/social",
      is_opinion: false,
      twitter_account: "@marketwatch",
      _score: 12.981401,
      _id: "de5c42bd743676d215ab8edd634678d0",
    },
    {
      title: "Tesla on Autopilot crashes into a parked truck in the US",
      author: "Reuters",
      published_date: "2023-06-27 04:27:57",
      published_date_precision: "full",
      link: "https://www.hindustantimes.com/car-bike/tesla-autopilot-crash-software-malfunction-elon-musk-car-101687838202825.html",
      clean_url: "hindustantimes.com",
      excerpt:
        "The Tesla was travelling in the middle lane when it struck the rear end of a Freightliner semi-truck that was parked in the same lane.",
      summary:
        "A Tesla vehicle that was operating on its Autopilot software crashed into a stationary truck on a highway in Pennsylvania on Friday night, police said, adding to scrutiny of the automaker's driver assistance system.\n \n \n \n \n \n \n \n \n2023 Tesla Model Y (Representative Image/AP)\n \n \n \nThe Tesla was travelling in the middle lane when it struck the rear end of a Freightliner semi-truck that was parked in the same lane and providing traffic control for a right lane closure, the Pennsylvania State Police said on Monday.",
      rights: "hindustantimes.com",
      rank: 980,
      topic: "news",
      country: "IN",
      language: "en",
      authors: "Reuters",
      media:
        "https://www.hindustantimes.com/ht-img/img/2023/06/27/1600x900/Behind-The-Wheel-Tesla-Model-Y-vs-Kia-EV6-GT-1_1687839052938_1687839302528.jpg",
      is_opinion: false,
      twitter_account: "@httweets",
      _score: 12.979471,
      _id: "4e30f61cf36f12be94a19e309f967978",
    },
    {
      title: "Tesla stellt neuen Auslieferungsrekord auf",
      author: "N-Tv Nachrichten",
      published_date: "2023-07-02 19:39:01",
      published_date_precision: "full",
      link: "https://www.n-tv.de/wirtschaft/Tesla-stellt-neuen-Auslieferungsrekord-auf-article24232996.html",
      clean_url: "n-tv.de",
      excerpt:
        "Von April bis Juni stellt Tesla knapp 480.000 Fahrzeuge her. Verglichen mit dem Vorjahr ist dies ein Anstieg um mehr als 85 Prozent und deutlich mehr als Analysten erwartet hatten. Auch bei den\u2026",
      summary:
        "Erwartungen klar \u00fcbertroffen\n \nTesla stellt neuen Auslieferungsrekord auf\n \n \n \n \n02.07.2023, 21:39 Uhr\n \n \n \n \n \n \n \n \nEin neuer Tesla wartet auf seine Auslieferung.\n \n(Foto: picture alliance / NurPhoto)\n \n \n \n \nVon April bis Juni stellt Tesla knapp 480.000 Fahrzeuge her. Verglichen mit dem Vorjahr ist dies ein Anstieg um mehr als 85 Prozent und deutlich mehr als Analysten erwartet hatten. Auch bei den Auslieferungen steht ein neuer Rekord. Dennoch werden die Lager voller.\n \nTesla hat im zweiten Quartal deutlich mehr Autos produziert und ausgeliefert als von Experten erwartet.",
      rights: "n-tv.de",
      rank: 3312,
      topic: "news",
      country: "DE",
      language: "de",
      authors: "N-Tv Nachrichten",
      media:
        "https://bilder3.n-tv.de/img/incoming/crop24232998/5151329883-cImg_16_9-w1200/412988560.jpg",
      is_opinion: false,
      twitter_account: "@ntvde",
      _score: 12.975979,
      _id: "2191e9b9837954aad0b67351ac9e9752",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://kdvr.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs/",
      clean_url: "kdvr.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs i\u2026",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "kdvr.com",
      rank: 3981,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://kdvr.com/wp-content/uploads/sites/11/2023/07/64a2c8290d00f8.39376667.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.964073,
      _id: "942827525558555529b98dca1a043225",
    },
    {
      title:
        "Tesla beats expectations with second quarter production and deliveries",
      author: "Ramishah Maruf",
      published_date: "2023-07-02 17:33:36",
      published_date_precision: "full",
      link: "https://www.cnn.com/2023/07/02/business/tesla-production-deliveries-second-quarter",
      clean_url: "cnn.com",
      excerpt:
        "Tesla beat expectations in the second quarter of 2023, announcing Sunday it produced nearly 480,000 vehicles and delivered over 466,000.",
      summary:
        "New York CNN \u2014\n\nTesla beat expectations in the second quarter of 2023, announcing Sunday it produced nearly 480,000 vehicles and delivered over 466,000.\n\nThe majority of production and deliveries were the Model 3 sedan and Model Y crossover, with 460, 211 produced and 446, 915 delivered. The electric car maker produced 19, 489 of the higher-priced Model X and Model S and delivered 19,225.\n\nDan Ives, an analyst at Wedbush Securities, said it was a 'trophy case quarter' for the company, adding 'Tesla bears,' or pessimistic Tesla investors, will be sent back into 'hibernation mode.",
      rights: "cnn.com",
      rank: 61,
      topic: "business",
      country: "US",
      language: "en",
      authors: "CNN,Ramishah Maruf",
      media:
        "https://media.cnn.com/api/v1/images/stellar/prod/230702124819-tesla-factory-germany-restricted.jpg?c=16x9&q=w_800,c_fill",
      is_opinion: false,
      twitter_account: "@CNNbusiness",
      _score: 12.962383,
      _id: "31c20c164778608c24a8fb78ddebdd0b",
    },
    {
      title:
        "Tesla ads may be appearing on Google already. Here's why it is significant",
      author: "Ht Auto Desk",
      published_date: "2023-06-29 04:30:32",
      published_date_precision: "full",
      link: "https://auto.hindustantimes.com/auto/electric-vehicles/tesla-ads-may-be-appearing-on-google-already-heres-why-it-is-significant-41688012096191.html",
      clean_url: "hindustantimes.com",
      excerpt:
        "Tesla has always avoided adveritising its electric cars. It has not had the need too. So what has changed now?",
      summary:
        "Tesla has long steered its path clear of advertising and instead, relied on its cult following to popularise its electric cars. But with mammoth ambitions and even bigger goals of selling more of its electric vehicles (EVs) across the world, the company has opted to test the waters of conventional marketing.\n \n \n \n \n \n \n \n \n \n \n \nTesla Model Y is the carmaker's second best-seller around the world with more than 11 units selling every hour.\n \n \n \n While Tesla CEO Elon Musk previously confirmed that his company would experiment with advertising in a small way, ads have reportedly already started appearing on Google.",
      rights: "hindustantimes.com",
      rank: 980,
      topic: "news",
      country: "IN",
      language: "en",
      authors: "HT Auto Desk",
      media:
        "https://images.hindustantimes.com/auto/img/2023/06/29/1600x900/tesla_model_y_1634896063865_1688012839484.jpg",
      is_opinion: false,
      twitter_account: "@HTAutotweets",
      _score: 12.959412,
      _id: "13b36ab6cad83f20c5c6a37456e96b64",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://fox4kc.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "fox4kc.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "fox4kc.com",
      rank: 7247,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://fox4kc.com/wp-content/uploads/sites/16/2023/07/64a2c823974400.26944710.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.95923,
      _id: "6f3313bdf11a18777199867a60c5cf6e",
    },
    {
      title: "Tesla Delivers Record-Setting 466,140 Cars In Q2 2023",
      author: "Eric Loveday",
      published_date: "2023-07-02 19:54:37",
      published_date_precision: "full",
      link: "https://insideevs.com/news/674654/tesla-q2-2023-deliveries-production/",
      clean_url: "insideevs.com",
      excerpt:
        "Tesla has just released its Q2 2023 production and delivery report, so the numbers are now in. See how Tesla fared this quarter right here.",
      summary:
        "Tesla\n has just released its Q2 2023 production and delivery report, so the numbers are now in. See how Tesla fared this quarter right here.\n \nAt 466,140 global deliveries of the \nModel Y\n, \nModel 3\n, \nModel S\n and \nModel X\n combined, Tesla beat expectations and set a new all-time record for deliveries in a single quarter.\n \nThe previous record was set by \nTesla in Q1 2022 at 422,875 cars sold\n.\u00a0\n \nTurning our attention back to the Q2 2023 results, here's the graphic showing the figures:\n \n \n \n \n \n \nFor Q2 2023, Tesla lists Model 3/Y deliveries at 446,915.",
      rights: "insideevs.com",
      rank: 7028,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Eric Loveday",
      media:
        "https://cdn.motor1.com/images/mgl/E616Oo/s1/from-left-tesla-model-s-tesla-model-3-tesla-model-x-and-tesla-model-y.jpg",
      is_opinion: false,
      twitter_account: "InsideEVs",
      _score: 12.95745,
      _id: "4ace83ebaba386f2b95ab1f65ab2f253",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://www.kxan.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "kxan.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "kxan.com",
      rank: 4404,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://www.kxan.com/wp-content/uploads/sites/40/2023/07/64a2c81e0599d3.45674418.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.952851,
      _id: "92723ef1aadcbe97d9520a1e61dcc7d4",
    },
    {
      title: "Tesla Model Y tekrardan zamland\u0131",
      author: "cumhuriyet.com.tr",
      published_date: "2023-06-28 11:30:00",
      published_date_precision: "timezone unknown",
      link: "https://www.cumhuriyet.com.tr/bilim-teknoloji/tesla-model-y-tekrardan-zamlandi-2094600",
      clean_url: "cumhuriyet.com.tr",
      excerpt:
        "ABD'li elektrikli otomotiv devi Tesla 2023'\u00fcn Nisan ay\u0131nda T\u00fcrkiye pazar\u0131na giri\u015f yapm\u0131\u015ft\u0131. T\u00fcrkiye'deki TL'nin d\u00f6viz kar\u015f\u0131s\u0131ndaki kayb\u0131 nedeniyle d\u00f6rt kez zamlanm\u0131\u015ft\u0131. \u015eimdi ise Tesla tekrar zam\u2026",
      summary:
        "Yay\u0131nlanma: 28.06.2023 - 14:08 \n \n \nG\u00fcncelleme: 28.06.2023 - 14:22\n \n \n \n \nAbone Ol\n \n \n \n \n \n\u00dcnl\u00fc i\u015f insan\u0131 Elon Musk'\u0131n sahip oldu\u011fu elektrikli ara\u00e7 \u00fcreticisi Tesla, T\u00fcrkiye'ye Nisan ay\u0131nda giri\u015f yapm\u0131\u015ft\u0131.\u00a0\n \nFirman\u0131n Model Y arac\u0131 T\u00fcrkiye'de beklenenden fazla talep g\u00f6rd\u00fc. Ancak ara\u00e7 d\u00f6viz kurlar\u0131 nedeniyle d\u00f6rt kez zamland\u0131. En son 8 Haziran'da yap\u0131lan zamla birlikte arac\u0131n fiyat\u0131 1 milyon 970 bin 258 TL olmu\u015ftu.\u00a0\n\n\n20 G\u00dcN SONRA TEKRAR ZAM\n\n\nShiftdelete'nin haberine g\u00f6re,\n 28 Haziran itibariyle Tesla Model Y'nin T\u00fcrkiye fiyat\u0131 tekrardan zamland\u0131 ve 2 milyon 181 bin 525 TL oldu.",
      rights: "cumhuriyet.com.tr",
      rank: 15059,
      topic: "news",
      country: "TR",
      language: "tr",
      authors: "cumhuriyet.com.tr",
      media:
        "https://www.cumhuriyet.com.tr/Archive/2023/6/28/2094600/kapak_140808.jpg",
      is_opinion: false,
      twitter_account: "@cumhuriyetgzt",
      _score: 12.947395,
      _id: "e9478212bd551b7f26d088f5fa734e21",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://www.woodtv.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "woodtv.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "woodtv.com",
      rank: 8767,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://www.woodtv.com/wp-content/uploads/sites/51/2023/07/64a2c823cfcf25.20109682.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.938461,
      _id: "fa3ef048c7a9baed773fd33f9728e379",
    },
    {
      title:
        "Polestar is the latest EV maker to announce a move to Tesla's North American charging standard",
      author: "John Rosevear",
      published_date: "2023-06-29 13:49:37",
      published_date_precision: "full",
      link: "https://www.cnbc.com/2023/06/29/polestar-moves-to-tesla-charging-standard.html",
      clean_url: "cnbc.com",
      excerpt:
        "Polestar owners will get access to Tesla's North American charging network starting in mid-2024.",
      summary:
        "Key Points\n\nPolestar has signed a deal with Tesla giving its owners access to Tesla's Superchargers in North America.\nNew Polestar vehicles sold in North America will have the Tesla-designed NACS plug standard starting in 2025.\nPolestar joins Ford, GM, Rivian and corporate sibling Volvo Cars in the move to the NACS standard.\n\nSwedish electric vehicle maker Polestar said Thursday that it has signed a deal with Tesla that will allow drivers of its EVs to charge at about 12,000 Tesla charging stations in North America starting next year.",
      rights: "cnbc.com",
      rank: 128,
      topic: "business",
      country: "US",
      language: "en",
      authors: "In Jrosevear,John Rosevear",
      media:
        "https://image.cnbcfm.com/api/v1/image/105764037-1551270453826polestar_2_001.jpg?v=1688046577&w=1920&h=1080",
      is_opinion: false,
      twitter_account: null,
      _score: 12.936216,
      _id: "502ebbe2c18389acc38debb2d4eda9f3",
    },
    {
      title: "Plug a non-Tesla into a Supercharger? It's not so simple",
      author: "Richard Truett",
      published_date: "2023-06-29 10:06:44",
      published_date_precision: "full",
      link: "https://www.autonews.com/mobility-report/making-non-teslas-work-superchargers-will-test-industry",
      clean_url: "autonews.com",
      excerpt:
        "GM, Ford, Rivian and Volvo \u2014 and other automakers contemplating making the switch \u2014 face challenges in designing and engineering their vehicles to be compatible with Tesla's charging network.",
      summary:
        'html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"\n\n\nFrom the wiring to the sheet metal to the software, automakers that plan to adopt Tesla\'s plug for their own EVs have bigger design and engineering challenges than just changing the receptacle in the charge port.\n\n\nSo far, \nGeneral Motors\n, \nFord\n, \nRivian\n and Volvo have committed to adopting Tesla\'s North American Charging Standard plugs. \nStellantis\n and \nHyundai\n have said they are considering making the same move.',
      rights: "autonews.com",
      rank: 2985,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "Automotive News,Richard Truett",
      media:
        "https://s3-prod.autonews.com/s3fs-public/styles/1200x630/public/TeslaPlug-MAIN_i.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: 12.930388,
      _id: "3d8e1a5f5bf1acb31e4385c66496910f",
    },
    {
      title:
        "Meta vs. Tesla: Who Wins This Clash of Titans in the Financial Arena?",
      author: "Investing.com",
      published_date: "2023-06-27 06:13:14",
      published_date_precision: "full",
      link: "https://www.investing.com/analysis/meta-vs-tesla-who-wins-this-clash-of-titans-in-the-financial-arena-200639425",
      clean_url: "investing.com",
      excerpt:
        "Stocks Analysis by Investing.com (Francesco Casarella/Investing.com) covering: Tesla Inc, Tesla Motors Inc, Meta Platforms Inc, Facebook Inc. Read Investing.com (Francesco Casarella/Investing.com)'s latest article on Investing.com",
      summary:
        "Elov Vs. Mark might or might not happen in reality\nBut, a Meta vs. Tesla 'financial' cage fight is certainly possible\nUsing InvestingPro, we compared Tesla and Meta over various financial metrics to determine a winner\nInvestingPro Summer Sale is on: Check out our massive discounts on subscription plans!\n\nElon Musk and Mark Zuckerberg have been taking shots at each other on social media lately. The latest development in their rivalry came on June 21, when Musk challenged Zuckerberg to a cage fight.",
      rights: "investing.com",
      rank: 1372,
      topic: "news",
      country: "ES",
      language: "en",
      authors: "Investing.com",
      media:
        "https://i-invdn-com.investing.com/redesign/images/seo/investingcom_analysis_og.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: 12.928652,
      _id: "f69df57994e106a4f40f07aa627f5457",
    },
    {
      title:
        "2 Prototipe Tesla Cybertruck Tertangkap Basah Diangkut Truk Trailer",
      author: "Wahyu Budi Santoso",
      published_date: "2023-06-27 13:22:00",
      published_date_precision: "full",
      link: "https://otomotif.sindonews.com/read/1139211/183/2-prototipe-tesla-cybertruck-tertangkap-basah-diangkut-truk-trailer-1687871164",
      clean_url: "sindonews.com",
      excerpt:
        "Viral di Twitter baru-baru ini ketika dua prototipe Tesla Cybertruck diangkut truk trailer di jalan raya di California. Viral di Twitter baru-baru ini ketika dua...",
      summary:
        "Viral Tesla Cybertruck diangkut truk trailer. FOTO/ TWITTER\n \n \nCALIFORNIA\n - Viral di Twitter baru-baru ini ketika dua prototipe \n \nTesla Cybertruck\n \ndiangkut truk trailer di jalan raya di California.\n \n Dengan munculnya prototipe tersebut, dipastikan Tesla akan menghadirkan lebih banyak model prototipe untuk diuji di pabrik Fremont.Seperti dilansir dari Mirror, sebagai catatan, dalam sepekan, foto viral tersebut merupakan yang kedua kalinya terlihat oleh pengguna jalan lain.Sebelumnya, model prototipe Cybertruck Tesla terlihat di sebuah trailer di dekat Mountain View California.",
      rights: "sindonews.com",
      rank: 29062,
      topic: "news",
      country: "ID",
      language: "id",
      authors: "Wahyu Budi Santoso",
      media:
        "https://pict.sindonews.net/dyn/850/pena/news/2023/06/27/183/1139211/2-prototipe-tesla-cybertruck-tertangkap-basah-diangkut-truk-trailer-wez.jpg",
      is_opinion: false,
      twitter_account: "@SINDOnews",
      _score: 12.923935,
      _id: "6ebc38761df466a235f18a67a62aef23",
    },
    {
      title:
        "Tesla vs Rivian: How the fresh EV startup compares to the electric-car giant",
      author: "Tim Levin",
      published_date: "2023-06-30 13:32:00",
      published_date_precision: "full",
      link: "https://www.businessinsider.com/tesla-vs-rivian",
      clean_url: "businessinsider.com",
      excerpt:
        "In the Tesla vs. Rivian debate, which electric car is better? Our in-depth guide covers pros and cons of each EV manufacturer.",
      summary:
        "For decades, a handful of Goliaths have dominated the auto industry. But the era of electrification has opened the door for smaller startups to enter the conversation.\u00a0\nCalifornia-based Rivian is one new firm competing with Tesla and gunning for a slice of the burgeoning electric-vehicle market.\u00a0\nI drove vehicles from both Rivian and Tesla to see how the up-and-comer compares to the EV industry leader.\u00a0\nWhat is Tesla?\n \n \n \n \n \n The Tesla Model X. \n \n Tesla \n \n \nTesla birthed the EV market as we know it and remains the most successful seller of electric cars in the world.",
      rights: "businessinsider.com",
      rank: 106,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Business Insider,Tim Levin",
      media:
        "https://i.insider.com/62e14f30d571050018adbe3a?width=1200&format=jpeg",
      is_opinion: false,
      twitter_account: "@CarsInsider",
      _score: 12.922867,
      _id: "790d0e0e8b04674d42ac1d4dce29ebc4",
    },
    {
      title: "BYD Beat Tesla in China Again. This Is a Two-Horse Race, Though.",
      author: "Al Root",
      published_date: "2023-07-02 22:05:00",
      published_date_precision: "full",
      link: "https://www.marketwatch.com/articles/byd-beat-tesla-in-china-ev-sales-67aa475d?mod=investing",
      clean_url: "marketwatch.com",
      excerpt:
        "The auto manufacturer sold more than 700,000 EVs in the second quarter, up almost 100% over last year.",
      summary:
        "Chinese EV maker BYD reported another impressive month, and quarter, of growth, besting even Tesla, which put up its own impressive numbers for the second quarter of 2023.\n\nSunday, BYD (ticker: 1211. Hong Kong) reported 251,685 electrified passenger vehicles sold in June. For the second quarter that means BYD sold more than 700,000 EVs, up almost 100% from the same time last year.\n\nBYD shares rose 4.5% in Hong Kong trading on Monday.\n\nBYD sells both plug-in hybrid vehicles and all-battery electric vehicles.",
      rights: "marketwatch.com",
      rank: 274,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Al Root",
      media: "https://images.barrons.com/im-784164/social",
      is_opinion: false,
      twitter_account: "@marketwatch",
      _score: 12.921607,
      _id: "7e8c120327970a5d47a3be3688f4d490",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://fox59.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "fox59.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "fox59.com",
      rank: 6649,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://fox59.com/wp-content/uploads/sites/21/2023/07/64a2c82180c591.41585773.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.919588,
      _id: "ab36a34fa4b6617b73b95c87588fb842",
    },
    {
      title:
        'Teslas Gigafactories weltweit im Vergleich: Darum ist das deutsche Tesla-Werk die "fortschrittlichste" und "effizienteste Anlage"',
      author: "Graham Rier 16:57",
      published_date: "2023-06-28 14:57:50",
      published_date_precision: "full",
      link: "https://www.businessinsider.de/wirtschaft/international-business/teslas-gigafactories-weltweit-im-vergleich-darum-ist-das-deutsche-tesla-werk-die-fortschrittlichsteund-effizienteste-anlage/",
      clean_url: "businessinsider.de",
      excerpt:
        "Die Gigafactory in Gr\u00fcnheide soll die fortschrittlichste weltweit sein. Dort produziert Tesla 5000 Autos pro Woche.",
      summary:
        "Eine Tesla-Gigafactory in Nevada.\n \nTesla\n \n \n \n \n \nTesla betreibt derzeit f\u00fcnf riesige Gigafactories, in denen Batterien und Elektrofahrzeuge hergestellt werden.\n\n\nDas Unternehmen plant au\u00dferdem den Bau einer sechsten \nGigafactory in Mexiko\n.\n\n\nHier ist ein Blick auf die Gigafactories von Tesla, von denen Elon Musk sagte, er wolle in den n\u00e4chsten Jahren zehn oder zw\u00f6lf bauen.\n \n \n \n Wir testen zurzeit maschinelle \u00dcbersetzungen von Artikeln unserer US-amerikanischen Kollegen von Insider. Dieser Artikel wurde automatisiert \u00fcbersetzt und von einem echten Redakteur \u00fcberpr\u00fcft.",
      rights: "businessinsider.de",
      rank: 3943,
      topic: "economics",
      country: "DE",
      language: "de",
      authors: "Amin Al Magrebi,Graham Rapier,Graham Rapier 16:57",
      media:
        "https://cdn.businessinsider.de/wp-content/uploads/2023/06/62e96f9057dd3c0018dc1548.webp?ver=1687959652",
      is_opinion: false,
      twitter_account: null,
      _score: 12.918934,
      _id: "79db5c80e42a91d7a4798f6e33f1d6c5",
    },
    {
      title:
        "Tesla set to report record quarterly vehicle deliveries, fueled by incentives",
      author: "",
      published_date: "2023-06-30 10:32:21",
      published_date_precision: "full",
      link: "https://www.moneycontrol.com/news/world/tesla-set-to-report-record-quarterly-vehicle-deliveries-fueled-by-incentives-10883591.html",
      clean_url: "moneycontrol.com",
      excerpt:
        "Tesla is expected as early as this weekend to report global deliveries of 445,000 vehicles in April to June, according to the average estimates of nine analysts by Refinitiv. That would be an increase of 5% from 422,875 the preceding quarter.",
      summary:
        "Tesla has cut prices aggressively since January, eroding its first-quarter margins.\n\nTesla is set to report record vehicle deliveries, after the top electric vehicle maker increased discounts and other incentives to boost sales in the face of economic uncertainty and rising competition.\n\nTesla CEO Elon Musk's plan to sharply increase sales this year faces challenges from aging and limited product line-ups as competition intensifies especially in China, and demand softens.\n\nTesla has cut prices aggressively since January, eroding its first-quarter margins.",
      rights: "moneycontrol.com",
      rank: 2753,
      topic: "news",
      country: "IN",
      language: "en",
      authors: "",
      media:
        "https://images.moneycontrol.com/static-mcnews/2020/11/TESLA-770x433.jpg",
      is_opinion: false,
      twitter_account: "@moneycontrolcom",
      _score: 12.918781,
      _id: "403d33bad73e73177eac691e144142fc",
    },
    {
      title: "Tesla steigert Fahrzeugauslieferungen um 83 Prozent",
      author: "Dieter Petereit",
      published_date: "2023-07-02 19:59:13",
      published_date_precision: "full",
      link: "https://t3n.de/news/tesla-steigert-fahrzeugauslieferungen-um-83-prozent-1562359/",
      clean_url: "t3n.de",
      excerpt:
        "Am Sonntag hat Tesla den aktuellen Bericht zum Stand seiner Produktion und Auslieferungen f\u00fcr das zweite Quartal 2023 ver\u00f6ffentlicht.",
      summary:
        "Tesla steigert Auslieferungen massiv. (Foto: Shutterstock / Zigres)\n \n \n \n \n \nWie \nder j\u00fcngste Quartalsbericht\n des US-amerikanischen Elektroautobauers zeigt, hat \nTesla\n im zweiten Quartal 2023 insgesamt 466.140 Fahrzeuge ausgeliefert und rund 13.000 Fahrzeuge mehr als ausgeliefert produziert. Damit \u00fcbertrifft Tesla erneut die Erwartungen der Analysten.\n \nUm deutliche 83 Prozent konnte Tesla seine Auslieferungen im Vorjahresvergleich steigern, was letztlich nicht v\u00f6llig \u00fcberraschend ist, weil der Hersteller seine Produktionskapazit\u00e4ten erweitert und die Produktion in seinem Fahrzeugmontagewerk im Hauptsitz in \nAustin\n im US-Bundesstaat Texas hochgefahren hat.",
      rights: "t3n.de",
      rank: 6103,
      topic: "news",
      country: "DE",
      language: "de",
      authors: "Dieter Petereit",
      media:
        "https://t3n.de/news/wp-content/uploads/2023/05/tesla-auf-gebaeude.jpg",
      is_opinion: false,
      twitter_account: "@t3n",
      _score: 12.9122305,
      _id: "ce5c4f58b5cf5360bf9f23f8a390b74b",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://www.koin.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "koin.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "koin.com",
      rank: 8592,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://www.koin.com/wp-content/uploads/sites/10/2023/07/64a2c82893e029.52845312.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.911334,
      _id: "d2505149b003e9b67153723d3b1b766a",
    },
    {
      title:
        "Inside Tesla's 18-wheeler Semi, which can travel 500 miles on one charge",
      author: "Pete Syme",
      published_date: "2023-07-02 09:28:00",
      published_date_precision: "full",
      link: "https://www.businessinsider.com/tesla-18-wheeler-semi",
      clean_url: "businessinsider.com",
      excerpt:
        "What is the Tesla 18 wheeler like? Look inside the electric Semi, find out what it is like to drive, and how far a battery charge can take it.",
      summary:
        "Tesla first announced its 18-wheeler semi truck in 2017, and made its first \nSemi delivery\n five years later to Pepsi after several \n18-wheeler production delays\n.\nOfficially named the Tesla Semi, it's the EV maker's first offering beyond passenger vehicles. \"If you're a trucker and you want the most badass rig on the road, this is it,\" Elon Musk said\u00a0last December.\nThere are two versions which, while fully loaded to an 87,000 lbs capacity, have maximum ranges of either 300 or 500 miles.\nWhile there are already some Tesla Semis on the roads, its pricing is unclear.",
      rights: "businessinsider.com",
      rank: 106,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Business Insider,Pete Syme",
      media:
        "https://i.insider.com/648c770b20f78100189fc546?width=1200&format=jpeg",
      is_opinion: false,
      twitter_account: "@CarsInsider",
      _score: 12.91114,
      _id: "c296cd7ebcd511c932d2c72e9cb9c987",
    },
    {
      title:
        "Tesla delivered 466,000 cars in another record quarter. Analysts called it a 'massive step in the right direction.'",
      author: "Aaron McDade",
      published_date: "2023-07-02 17:15:00",
      published_date_precision: "full",
      link: "https://news.yahoo.com/tesla-delivered-466-000-cars-171500317.html",
      clean_url: "yahoo.com",
      excerpt:
        "Elon Musk's car company produced almost 480,000 vehicles in the three months to June 30, but that still exceeded deliveries.",
      summary:
        "Tesla posted another record quarter for the three months to June 30, it said on Sunday.\nThe EV leader produced nearly 480,000 vehicles and delivered about 466,000, Tesla said.\nIt's another indication Tesla's strategy of starting to operate like other auto makers is working.\nTesla posted another record quarter for both production and deliveries in the three months to June 30.\nThe EV market leader said Sunday that it produced 479,700 cars, and delivered 466,140 \u2013 both exceeding the totals for the first quarter of this year.",
      rights: "yahoo.com",
      rank: 31,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Aaron McDade",
      media:
        "https://s.yimg.com/ny/api/res/1.2/lt4eCvILq0h1wFGtX39qBQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA-/https://media.zenfs.com/en/business_insider_articles_888/76ba89a8fe067c376c442a5d8978e769",
      is_opinion: false,
      twitter_account: "@YahooNews",
      _score: 12.909027,
      _id: "213cfc8ba99c409f46b63c0ad70ee74f",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://www.wavy.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "wavy.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "wavy.com",
      rank: 7387,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://www.wavy.com/wp-content/uploads/sites/3/2023/07/64a2c829e23e96.77570032.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.908994,
      _id: "c593c1929818cc4a4e3ec4887f3f94ae",
    },
    {
      title:
        "Cathie Wood Offloads Whopping $19M Tesla Stock Even As Bulls Brace For Q2 Deliveries Sunday",
      author: "Shanthi Rexaline",
      published_date: "2023-07-01 02:44:58",
      published_date_precision: "full",
      link: "https://www.benzinga.com/analyst-ratings/analyst-color/23/06/33088270/cathie-wood-offloads-whopping-19m-tesla-stock-even-as-bulls-brace-for-q2-deliveries",
      clean_url: "benzinga.com",
      excerpt: "",
      summary:
        "Cathie Wood's Ark Invest\n sold a massive chunk of \nTesla Inc.\n \nTSLA\n shares just ahead of the electric vehicle maker's \nsecond-quarter deliveries report.\nWhat Happened:\n On Friday, Wood's Ark Invest, through its \nArk Innovation ETF\n \nARKK\n and \nArk Next Generation Internet ETF\n \nARKW\n, sold 72,183 Tesla shares, valued at about $18.9 million.\nArk has been a seller of Tesla stock in the recent past, as the stock continued to grind higher. The fund's net buying so far this year is positive with a tally of 1.",
      rights: "benzinga.com",
      rank: 1933,
      topic: "finance",
      country: "US",
      language: "en",
      authors: "Benzinga Editor,Shanthi Rexaline",
      media:
        "https://cdn.benzinga.com/files/images/story/2023/ARK_Photo_by_viewimage_on_Shutterstock_1.jpeg?width=1200&height=800&fit=crop",
      is_opinion: false,
      twitter_account: "@benzinga",
      _score: 12.904884,
      _id: "c2c9cbce925be74cdc462a2ef3a2e5c3",
    },
    {
      title:
        "Lockouts, Trapped Owners Raise Concerns About Tesla EVs Reliability",
      author: "John Lopez",
      published_date: "2023-07-02 15:06:07",
      published_date_precision: "full",
      link: "https://www.techtimes.com/articles/293304/20230702/lockouts-trapped-owners-raise-concerns-tesla-evs-reliability.htm",
      clean_url: "techtimes.com",
      excerpt:
        "Recent Tesla battery failures, including dead 12-volt batteries and power losses, raise concerns about the reliability of their electric vehicles.",
      summary:
        "John Lopez\n, Tech Times \n02 July 2023, 11:07 am\n \n \nTesla, the frontrunner in the electric vehicle (EV) market, has been making waves with its innovative technology. In fact, according to Bloomberg, shares of Tesla Inc. have increased 109% this year.\n \nBut there have been recent reports, including some from last year, by Tesla owners who have had problems getting into their vehicles because of battery failures.\u00a0\n \nThese issues have varied from dead 12-volt batteries to unexpected power losses. These cases are making people wonder if Tesla's electric vehicles can be trusted.",
      rights: "All articles are copyrighted by Tech Times",
      rank: 2599,
      topic: "tech",
      country: "US",
      language: "en",
      authors: "John Lopez",
      media:
        "https://1734811051.rsc.cdn77.org/data/images/full/416385/tesla.jpg",
      is_opinion: false,
      twitter_account: "@TechTimes_News",
      _score: 12.903205,
      _id: "677137f8766c5d24d12e535e32b4a4c1",
    },
    {
      title: "Mobil Listrik Murah Tesla Diprediksi Hadir Awal 2025",
      author: "Wahyu Sibarani",
      published_date: "2023-06-28 03:11:21",
      published_date_precision: "full",
      link: "https://otomotif.sindonews.com/read/1139553/120/mobil-listrik-murah-tesla-diprediksi-hadir-awal-2025-1687921610",
      clean_url: "sindonews.com",
      excerpt:
        "Tesla diperkirakan akan menghadirkan mobil listrik murah mereka pada awal 2025. Bagaimana detail persiapannya? Tesla diperkirakan akan menghadirkan mobil listrik...",
      summary:
        "Mobil listrik murah Tesla yang harganya Rp300 jutaan hanya akan diproduksi di pabrik Tesla yang ada di Meksiko. Foto/Ruido en Lared\n \n \nJAKARTA\n - Tesla diperkirakan akan menghadirkan mobil listrik murah mereka pada awal 2025. Hal itu terungkap setelah Tesla meminta beberapa suplier parts mobil listrik yang ada di China untuk memuluskan rencana pembuatan mobil listrik murah tersebut.Tidak main-main Tesla meminta sebanyak 20 suplier komponen di China untuk membuat pabrik komponen langsung di tempat mobil listrik murah Tesla itu dibuat.",
      rights: "2023 SINDOnews. All rights reserved.",
      rank: 29062,
      topic: "news",
      country: "ID",
      language: "id",
      authors: "Wahyu Sibarani",
      media:
        "https://pict.sindonews.net/dyn/850/pena/news/2023/06/28/120/1139553/mobil-listrik-murah-tesla-diprediksi-hadir-awal-2025-rbz.jpg",
      is_opinion: false,
      twitter_account: "@SINDOnews",
      _score: 12.902794,
      _id: "b30f50f330f2205b9c1048e918b527fc",
    },
    {
      title:
        "Tesla Reported 466,140 Deliveries for the Second Quarter, and Production of 479,700 Vehicles",
      author: "Lora Kolodny",
      published_date: "2023-07-02 17:30:00",
      published_date_precision: "timezone unknown",
      link: "https://www.nbcconnecticut.com/news/business/money-report/tesla-reported-466140-deliveries-for-the-second-quarter-and-production-of-479700-vehicles/3059739",
      clean_url: "nbcconnecticut.com",
      excerpt:
        "Tesla just posted its second-quarter vehicle production\u00a0and deliveries report for 2023.",
      summary:
        "Tesla just posted its second-quarter vehicle production and deliveries report for 2023.\n\nDeliveries are the closest approximation of sales disclosed by Elon Musk's electric vehicle business.\n\nTesla does not break out its deliveries by individual model or region.\n\nTesla posted its second-quarter vehicle production and delivery report for 2023 on Sunday.\n\nHere are the key numbers from the electric vehicle maker:\n\nTotal deliveries Q2 2023: 466,140\n\nGet Connecticut local news, weather forecasts and entertainment stories to your inbox.",
      rights: "nbcconnecticut.com",
      rank: 7083,
      topic: "business",
      country: "US",
      language: "en",
      authors: "CNBC,Lora Kolodny,Lora Kolodny Cnbc",
      media:
        "https://media.nbcconnecticut.com/2023/07/106857488-16164350972021-03-22t172150z_1971118209_rc2hgm9cxd3j_rtrmadp_0_usa-stocks-tesla.jpeg?quality=85&strip=all&resize=1200%2C675",
      is_opinion: false,
      twitter_account: "@nbcconnecticut",
      _score: 12.901557,
      _id: "d11e9ee652a19cbd409baaa6ab7d79ce",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://myfox8.com/automotive/internet-brands/will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "myfox8.com",
      excerpt:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that [\u2026]",
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "myfox8.com",
      rank: 7994,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson",
      media:
        "https://myfox8.com/wp-content/uploads/sites/17/2023/07/64a2c829034210.00870013.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.90081,
      _id: "af7f4ceb8d24cb5d66031704d7f3ff7b",
    },
    {
      title:
        "Tesla mit Update: Bald Unterst\u00fctzung von Drittanbieter-Apps?",
      author: "Rui Filipe Martins Machado",
      published_date: "2023-06-29 13:15:00",
      published_date_precision: "full",
      link: "https://www.computerbild.de/artikel/cb-News-Connected-Car-Tesla-mit-Update-Bald-Unterstuetzung-von-Drittanbieter-Apps-36078843.html",
      clean_url: "computerbild.de",
      excerpt:
        "Seit Jahren warten Tesla-Fans auf die Einf\u00fchrung von Drittanbieter-Apps. Nun scheint Tesla aktiv daran zu arbeiten. Darauf deutet zumindest ein neues Update hin.",
      summary:
        "\u00d6ffnet Tesla sein System nun offiziell f\u00fcr Drittanbieter-Apps?\n Foto: iStock.com/helivideo\nSeit Jahren warten Tesla-Fans auf die offizielle Unterst\u00fctzung von Drittanbieter-Apps. Nun scheint Tesla aktiv daran zu arbeiten. Darauf deutet zumindest ein neues Update hin.\nNavigation, und sogar Gaming haben \nTeslas\n bereits auf dem Kasten. In Zukunft k\u00f6nnte der Funktionsumfang des Tesla-Bordsystems aber rasant zunehmen. Denn nach einem Update liefert die offizielle Tesla-App Hinweise darauf, dass der US-Elektroautobauer des Milliard\u00e4rs \nElon Musk\n das Betriebssystem seiner Stromer bald f\u00fcr Drittanbieter-Apps \u00f6ffnen k\u00f6nnte.",
      rights: "Copyright COMPUTER BILD",
      rank: 8266,
      topic: "news",
      country: "DE",
      language: "de",
      authors: "Rui Filipe Martins Machado",
      media:
        "https://i.computer-bild.de/imgs/1/4/9/1/8/3/7/5/tesla-app-store-4ea753f04faed14b.jpg",
      is_opinion: false,
      twitter_account: "@computerbild",
      _score: 12.894957,
      _id: "594e7bcefaf4540bf7cfa12eb89383eb",
    },
    {
      title: "Tesla Stock Jumps. No News Is Good News.",
      author: "Al Root",
      published_date: "2023-06-27 14:05:00",
      published_date_precision: "full",
      link: "https://www.barrons.com/articles/tesla-stock-price-news-4f754b20",
      clean_url: "barrons.com",
      excerpt:
        "For the electric-vehicle maker, no news is good news after analysts bumped down its stock four times in four days.",
      summary:
        "Updated June 27, 2023 1:40 pm ET / Original June 27, 2023 10:05 am ET\n\n\n\n \n Order Reprints \n \n Print Article \n\n\n \n \n \n\n\n \n \nTo call recent trading in Tesla stock wild is to forget trading in \n \n Tesla \n \n stock is always wild. \n \n \n \nAlready a subscriber? \n Sign In \n \n \n\n\n \n \n \n \n\n\n \n \n \n \nTo call recent trading in Tesla stock wild is to forget trading in Tesla stock is always wild.\n \nAn error has occurred, please try again later.\n \n \n \n\n \nThis article has been sent to",
      rights: "barrons.com",
      rank: 1377,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Al Root",
      media: "https://images.barrons.com/im-807609/social",
      is_opinion: false,
      twitter_account: "@DowJonesAl",
      _score: 12.893668,
      _id: "16e4f8866b6a947b4a120aae429843cb",
    },
    {
      title:
        "Tesla on Autopilot rear-ends work truck along Pennsylvania interstate, police say",
      author: "Aislinn Murphy",
      published_date: "2023-06-27 22:04:27",
      published_date_precision: "full",
      link: "https://www.foxbusiness.com/technology/tesla-autopilot-rear-ends-work-truck-along-pennsylvania-interstate-police-say",
      clean_url: "foxbusiness.com",
      excerpt:
        "Pennsylvania State Police said an 18-year-old was operating his Tesla on Autopilot when the car lost control and rear-ended a work truck along a busy interstate.",
      summary:
        "A Tesla on Autopilot\n slammed into the back of a work truck along a Pennsylvania interstate on Friday night, according to police.\n \nPennsylvania State Police (PSP)\n said the Tesla was driving in the middle lane of I-76 east when it rear-ended a Freightliner semi-truck that was parked in the same lane and providing traffic control for a lane closure.\nPSP said the electric car lost control due to the fact it was operating on its Autopilot software.\u00a0\n \n \n \n \n \n \nA Tesla rear-ended a work truck along a busy stretch of Pennsylvania interstate because the electric car was on Autopilot, police said.",
      rights: "foxbusiness.com",
      rank: 915,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Aislinn Murphy",
      media:
        "https://a57.foxnews.com/static.foxbusiness.com/foxbusiness.com/content/uploads/2023/02/0/0/Tesla-Logo.jpg?ve=1&tl=1",
      is_opinion: false,
      twitter_account: "@FoxBusiness",
      _score: 12.893334,
      _id: "f057ac41bd70ec736b43291879eb4e8f",
    },
    {
      title:
        "I own a \u00a344k Tesla Model S but here's ten reasons why you DON'T want it",
      author: "Jorge Hinojosa Mena",
      published_date: "2023-06-27 15:32:27",
      published_date_precision: "full",
      link: "https://www.thesun.ie/motors/10948752/own-tesla-reasons-why-you-dont-want-it/",
      clean_url: "thesun.ie",
      excerpt:
        "A TESLA owner has slammed the electric car after buying the Model S for a whopping \u00a344k \u2013 listing ten huge problems he's encountered. Myong Hong claims he's been inundated with is\u2026",
      summary:
        "A TESLA owner has slammed the electric car after buying the Model S for a whopping \u00a344k - listing ten huge problems he's encountered.\n\n\nMyong Hong claims he's been inundated with issues since buying the car and even urged others not to buy the vehicle that has taken the world by storm.\u00a0\n\n\nA man who owns a \u00a344,000 Tesla Model S has revealed the ten key problems he has found in his electric cars\nCredit: YouTube @CameraToFreedom \n\n\nHe said that the price of charging your car varies depending on the time of the day, you can only repair your Tesla at official repair centres, and they haven't included a spare tyre to make their car lighter.",
      rights: "thesun.ie",
      rank: 6724,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "Jorge Hinojosa Mena",
      media:
        "https://www.thesun.ie/wp-content/uploads/sites/3/2023/06/newspress-collage-22829440-1687872403929.jpg?1687883792&strip=all&quality=100&w=1920&h=1080&crop=1",
      is_opinion: false,
      twitter_account: "@IrishSunOnline",
      _score: 12.89293,
      _id: "15eba4ef360f5469507600c6ebd74ec6",
    },
    {
      title: "Electrify America adding Tesla charging",
      author: "Stephen Edelstein",
      published_date: "2023-06-30 12:00:00",
      published_date_precision: "full",
      link: "https://kdvr.com/automotive/internet-brands/electrify-america-adding-tesla-charging/",
      clean_url: "kdvr.com",
      excerpt:
        "Electrify America on Thursday announced that it will add Tesla connectors to its charging network in the U.S. and Canada. The company said in a press release that it will continue to provide Combin\u2026",
      summary:
        "Electrify America on Thursday announced that it will add Tesla connectors to its charging network in the U.S. and Canada.\n\nThe company said in a press release that it will continue to provide Combined Charging Standard (CCS) connectors, while also adding the Tesla connector, branded by Tesla as the North American Charging Standard (NACS) as an option at existing and future charging sites by 2025.\n\n'Since our founding, we have focused on building an inclusive and open hyper-fast charging network to facilitate the adoption of electric vehicles,' Electrify America CEO Robert Barrosa said in a statement.",
      rights: "kdvr.com",
      rank: 3981,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Stephen Edelstein",
      media:
        "https://kdvr.com/wp-content/uploads/sites/11/2023/06/649ed665571cd8.58492326.jpg?w=1280",
      is_opinion: false,
      twitter_account: null,
      _score: 12.889277,
      _id: "1df6952cec9cf7fe2367b0bdd10efd2f",
    },
    {
      title: "Will Tesla Supercharger reliability extend to other brands' EVs?",
      author: "Bengt Halvorson",
      published_date: "2023-07-02 12:00:00",
      published_date_precision: "full",
      link: "https://www.greencarreports.com/news/1140101_will-tesla-supercharger-reliability-extend-to-other-brands-evs",
      clean_url: "greencarreports.com",
      excerpt: null,
      summary:
        "A shift to Tesla's NACS connector in future EVs, and Tesla Supercharger compatibility even sooner, has now been announced by enough automakers to declare it the majority charging standard for EVs in North America for the foreseeable future. And while automaker press releases and statements have pointed primarily to the number of charge points that the Tesla network adds, there's a subtext to it all that's arguably much more important: reliability.\n\nThat reliability, as the federal government is starting to keep tabs on, isn't guaranteed, and it will be a litmus test of what Tesla has built and whether it can make the translation.",
      rights: "greencarreports.com",
      rank: 10463,
      topic: "business",
      country: "US",
      language: "en",
      authors: "Bengt Halvorson,Senior Editor,Stephen Edelstein",
      media:
        "https://images.hgmsites.net/hug/tesla-supercharger_100875195_h.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: 12.886712,
      _id: "a55bc3a8de8093febe638cf812e09bcc",
    },
  ],
  user_input: {
    q: "Tesla",
    search_in: ["title_summary"],
    lang: null,
    not_lang: null,
    countries: null,
    not_countries: null,
    from: "2023-06-27 00:00:00",
    to: null,
    ranked_only: "True",
    from_rank: null,
    to_rank: null,
    sort_by: "relevancy",
    page: 1,
    size: 50,
    sources: null,
    not_sources: [],
    topic: null,
    published_date_precision: null,
  },
};
